import { useMemo, useState } from 'react'
import { Link, useSearchParams } from 'react-router-dom'
import { ArrowRight, ArrowUpRight, BadgeCheck, Check, ChevronRight, CirclePlay, Clock3, Filter, Heart, LockKeyhole, Mail, MoreHorizontal, Play, Search, Share2, ShieldCheck, Sparkles, Star, Users, Video, WandSparkles } from 'lucide-react'
import { categories, courses, modules, reviews } from './data'
import { Avatar, Breadcrumbs, Button, CategoryCard, CourseCard, CourseCover, CourseNav, CourseStats, FilterSelect, HappyStudentsCard, LessonRow, PageShell, ProgressCard, QuoteMark, RatingStars, ReadMore, SearchBox, SectionHeading } from './components'

const course = courses[0]
const courseTitle = 'Build Digital Asset: A Comprehensive Guide'

export function HomePage() {
  return <PageShell darkHeader>
    <section className="home-hero">
      <div className="hero-grid" />
      <span className="hero-shape hero-ribbon"/><span className="hero-shape hero-cone"/><span className="hero-shape hero-loop"/><span className="hero-shape hero-squiggle"/>
      <div className="wrap home-hero-content"><h1>Get Access to Hundreds<br className="desktop-break"/> Courses Available</h1><p>Unlock your creativity, gain valuable knowledge, and grow your business with our wide range of courses.</p><SearchBox /></div>
      <div className="hero-orbit"/><div className="hero-stage"><div className="hero-person"><span className="person-hair"/><span className="person-head"/><span className="person-neck"/><span className="person-body"/><span className="person-laptop"/><span className="person-headphone"/></div></div>
      <div className="hero-course-float glass-card"><b>UI/UX Design</b><span>200 Courses <i>•</i> 1000+ Students</span></div><ProgressCard/><HappyStudentsCard/>
    </section>
    <section className="partner-strip wrap"><span>Trusted by creative teams at</span><div className="partner-logos"><b>↗ figma</b><b>◩ Webflow</b><b>◉ notion</b><b>✦ Shopify</b><b>◒ miro</b></div></section>
    <section className="section wrap home-categories"><SectionHeading centered title="Discover Your Passion, Build Your Skills" description="At ByteSpace Courses, we bring you closer to life-changing knowledge. Explore a variety of courses across different fields, from technology to the arts, and make a difference in your career and life."/><div className="category-grid">{categories.map(item => <CategoryCard category={item} key={item.name}/>)}</div><div className="center-action"><Button variant="outline">Explore all categories <ArrowRight size={17}/></Button></div></section>
    <section className="section courses-section"><div className="wrap"><div className="section-row"><SectionHeading eyebrow="LEARN SOMETHING NEW" title="Popular Courses" description="Learn from experienced creators and grow your skills, one course at a time."/><Link className="text-link" to="/search">Browse all courses <ArrowRight size={17}/></Link></div><div className="course-grid">{courses.slice(0,3).map(item => <CourseCard course={item} key={item.title}/>)}</div><div className="course-grid course-grid-extra">{courses.slice(3,6).map(item => <CourseCard course={item} key={item.title}/>)}</div></div></section>
    <section className="creator-promo wrap"><div className="creator-promo-art"><span className="promo-orb"/><div className="promo-note"><Sparkles/><b>Make something<br/>people love.</b></div><div className="promo-tag">Your next chapter starts here <ArrowUpRight size={16}/></div></div><div className="creator-promo-copy"><span className="eyebrow">FOR THE CURIOUS</span><h2>Learn from creators who love what they do.</h2><p>Explore practical, thoughtfully crafted courses from people working at the edge of their fields. Build useful skills at your own pace.</p><div className="promo-checks"><span><Check/>Learn by doing</span><span><Check/>Go at your own pace</span><span><Check/>Keep lifetime access</span></div><Link to="/search"><Button>Explore the library <ArrowRight size={17}/></Button></Link></div></section>
    <section className="community-section"><div className="wrap community-inner"><div><span className="eyebrow eyebrow-light">CREATE WITH US</span><h2>Turn your knowledge into someone else's next big idea.</h2><p>Share your expertise, build your audience, and create a community around what you love.</p><Link to="/creator"><Button>Become a creator <ArrowRight size={17}/></Button></Link></div><div className="community-stat"><strong>10K<span>+</span></strong><span>learners and creators growing together</span><div className="community-avatars"><Avatar initials="JD"/><Avatar initials="RM" tone={1}/><Avatar initials="AF" tone={3}/><Avatar initials="LY" tone={4}/><i>+</i></div></div></div></section>
    <section className="section testimonial-section wrap"><div className="section-row"><SectionHeading eyebrow="REAL STORIES" title="Discover What Our Community Is Saying"/><p className="testimonial-intro">At ByteSpace, our vibrant community of learners and creators is at the heart of what we do. Hear directly from those who have experienced the transformative journey of learning and creating.</p></div><div className="testimonial-grid">{[{name:'Sarah M.',role:'Enthusiastic Learner',initials:'SM',body:'“ByteSpace has transformed my approach to learning. The diverse range of courses and the quality of content have exceeded my expectations.”'},{name:'James L.',role:'Lifelong Learner',initials:'JL',body:'“The vibrant community and variety of courses make ByteSpace a go-to platform for continuous skill development.”'},{name:'Alex B.',role:'Inspired Creator',initials:'AB',body:'“The Course Editor is user-friendly, and the support from the community is incredible. It’s fulfilling to see my courses making an impact.”'}].map((item,i)=><article className="testimonial-card" key={item.name}><Avatar initials={item.initials} tone={i} size="large"/><h3>{item.name}</h3><span className="muted">{item.role}</span><RatingStars/><p>{item.body}</p><QuoteMark/></article>)}</div></section>
  </PageShell>
}

function AuthPage({ mode }: { mode: 'register' | 'login' }) {
  const isRegister = mode === 'register'
  return <PageShell><section className="auth-page wrap"><div className="auth-pitch"><span className="eyebrow">BYTESPACE · YOUR NEXT CHAPTER</span><h1>{isRegister ? 'Sign up and come in' : 'Sign in with ease'}</h1><p>{isRegister ? 'The registration process is straightforward, uncomplicated, and efficient, allowing you to get started quickly and at no cost.' : 'Experience a seamless and efficient sign-in process that grants you instant access to a world of knowledge.'}</p><div className="auth-art"><span className="auth-art-orbit"/><span className="auth-art-disc"/><span className="auth-art-star">✳</span><div className="auth-art-card"><span>YOUR CREATIVE SPACE</span><b>Learn.<br/>Make.<br/>Grow.</b><i>ByteSpace / 001</i></div><div className="auth-art-chip"><Sparkles size={19}/></div></div></div><form className="auth-card" onSubmit={e=>e.preventDefault()}><span className="eyebrow">{isRegister ? 'CREATE AN ACCOUNT' : 'WELCOME BACK'}</span><h2>{isRegister ? 'Welcome to ByteSpace' : 'Welcome Back'}</h2><p>{isRegister ? 'Create your account and start learning today.' : 'Sign in to pick up right where you left off.'}</p>{isRegister && <label className="field"><span>Full Name</span><input autoComplete="name" placeholder="Jamie Davis" /></label>}<label className="field"><span>Email</span><span className="field-input"><Mail size={17}/><input type="email" autoComplete="email" placeholder="designer@example.com"/></span></label><label className="field"><span>Password</span><span className="field-input"><LockKeyhole size={17}/><input type="password" autoComplete={isRegister?'new-password':'current-password'} placeholder="Enter your password"/></span></label>{!isRegister && <div className="forgot-row"><label><input type="checkbox"/> Remember me</label><a href="#forgot">Forgot password?</a></div>}{isRegister && <label className="terms-check"><input type="checkbox"/> <span>I agree to ByteSpace's <a href="#terms">Terms of Service</a> and <a href="#privacy">Privacy Policy</a>.</span></label>}<Button type="submit" className="auth-submit">{isRegister ? 'Continue' : 'Sign In'} <ArrowRight size={17}/></Button>{!isRegister && <div className="auth-divider"><span>or</span></div>}<div className="auth-switch">{isRegister ? 'Already have an account?' : 'New user?'} <Link to={isRegister?'/login':'/register'}>{isRegister?'Login':'Create an account'}</Link></div></form></section></PageShell>
}
export function RegisterPage(){ return <AuthPage mode="register"/> }
export function LoginPage(){ return <AuthPage mode="login"/> }

export function SearchPage() {
  const [searchParams, setSearchParams] = useSearchParams()
  const [query,setQuery]=useState(searchParams.get('q')??'')
  const [active,setActive]=useState('All courses')
  const filtered=useMemo(()=>courses.filter(item=>(!query || `${item.title} ${item.creator} ${item.tag}`.toLowerCase().includes(query.toLowerCase()))&&(active==='All courses'||item.tag===active)),[active,query])
  const tags=['All courses','Design','Technology','Business','Lifestyle']
  return <PageShell><section className="search-hero"><div className="wrap"><Breadcrumbs items={['Home','Courses']}/><span className="eyebrow">THE BYTESPACE LIBRARY</span><h1>Find your next<br className="mobile-break"/> great idea.</h1><p>Learn something you love from people who are great at it.</p><SearchBox value={query} onChange={v=>{setQuery(v);setSearchParams(v?{q:v}:{})}}/><div className="search-proof"><Users size={17}/><span>Join over 10,000 learners building their next skill</span></div></div></section><section className="section wrap search-results"><div className="search-result-top"><div><span className="eyebrow">COURSE LIBRARY</span><h2>Explore courses <span className="result-count">({filtered.length})</span></h2></div><FilterSelect label="Sort by" value="Most popular"/></div><div className="search-toolbar"><div className="filter-tabs">{tags.map(tag=><button key={tag} onClick={()=>setActive(tag)} className={active===tag?'filter-tab-active':''}>{tag}</button>)}</div><button className="filter-button"><Filter size={17}/> Filters <span className="filter-badge">2</span></button></div><div className="course-grid">{filtered.length?filtered.map(item=><CourseCard course={item} key={item.title}/>):<div className="empty-results"><Search/><h3>No courses found</h3><p>Try another topic or category.</p></div>}</div><div className="pagination"><button aria-label="Previous page">‹</button><button className="page-active">1</button><button>2</button><button>3</button><span>…</span><button>10</button><button aria-label="Next page">›</button></div></section></PageShell>
}

function CourseIntro({ active = 'About' }: { active?: string }) {
  return <><section className="course-page-hero wrap"><Breadcrumbs items={['Home','Courses','Design',courseTitle]}/><div className="course-intro-grid"><div className="course-intro-copy"><span className="eyebrow">DESIGN · DIGITAL CREATIVITY</span><h1>{courseTitle}</h1><p>Unlock the power of digital creation with expert guidance.</p><div className="creator-inline"><Avatar initials="PP" tone={4}/><span>by <b>purepearl studio</b><BadgeCheck size={15}/></span><span className="creator-separator">·</span><span>Professional Creator</span></div><CourseStats/><div className="course-hero-actions"><Link to="/lessons"><Button>Start learning <ArrowRight size={17}/></Button></Link><button className="share-button"><Share2 size={17}/> Share course</button></div></div><div className="course-intro-art"><CourseCover course={course} large/><button className="video-play" aria-label="Play course preview"><Play size={24} fill="currentColor"/></button><span className="video-time"><Video size={15}/> Course preview</span></div></div><CourseNav active={active}/></section></>
}

function CourseAside() {
  return <aside className="course-aside"><div className="enroll-card"><div className="aside-price">$25 <small>/ lifetime</small></div><p>Get lifetime access to the complete course and all future updates.</p><Link to="/lessons"><Button className="full-button">Enroll Now <ArrowRight size={17}/></Button></Link><div className="safe-note"><ShieldCheck size={16}/>30-day money-back guarantee</div><h3>This course includes</h3><ul><li><CirclePlay/>112 lessons on-demand</li><li><Clock3/>24 hours of video</li><li><WandSparkles/>Downloadable resources</li><li><BadgeCheck/>Certificate of completion</li><li><Heart/>Lifetime access</li></ul></div><div className="instructor-card"><div className="instructor-top"><Avatar initials="PP" tone={4} size="large"/><div><h3>PurePearl Studio</h3><span>Professional Creator</span></div></div><p>Passionate UI/UX and web designer sharing a love of thoughtful digital experiences.</p><Link to="/creator" className="text-link">See full profile <ArrowRight size={15}/></Link></div></aside>
}

export function CourseDetailsPage() {
  return <PageShell><CourseIntro/><div className="wrap course-body-layout"><article className="course-main-column"><SectionHeading title="Description"/><ReadMore><p>Embark on an enlightening exploration into the world of digital creation with our comprehensive course, “Build Digital Assets: A Comprehensive Guide.” This transformative learning experience invites you to delve into the intricacies of crafting impactful digital content. From foundational concepts to advanced techniques, this guide is curated to empower you with the skills essential for navigating the dynamic landscape of digital asset creation.</p><p>Explore the design principles behind impactful creations, practice effective visual communication, and apply your learning with hands-on exercises.</p></ReadMore><div className="sneak-peek"><div className="sneak-peek-art"><CourseCover course={course}/><button className="video-play"><Play fill="currentColor"/></button></div><div><span className="eyebrow">SNEAK PEEK</span><h3>Get a taste of what's inside</h3><p>Take a look at how we break down each concept into practical, approachable lessons.</p></div></div><div className="key-points"><SectionHeading title="What you'll learn"/><div className="key-point-grid">{['Foundational concepts','Design principles mastery','Advanced creation techniques','Project showcase and critique','Optimize for every platform','Digital asset management','Monetization strategies','Build your portfolio'].map(x=><span key={x}><Check/>{x}</span>)}</div></div><section className="course-lessons-preview"><div className="section-row"><SectionHeading title="Course content" description="112 lessons · 24 hours total"/><Link to="/lessons" className="text-link">View all lessons <ArrowRight size={15}/></Link></div>{modules.slice(0,3).map((item,i)=><div className="module-row" key={item.title}><span className="module-index">0{i+1}</span><span>{item.title}</span><span>{item.count} lessons</span><ChevronRight size={18}/></div>)}</section></article><CourseAside/></div></PageShell>
}

export function LessonsPage() {
  return <PageShell><CourseIntro active="Lessons"/><div className="wrap lessons-page"><div className="lessons-heading"><div><span className="eyebrow">COURSE CURRICULUM</span><h2>Explore the Modules</h2><p>Immerse yourself in the course content through comprehensive lessons, practical insights, and hands-on experiences.</p></div><div className="curriculum-count"><strong>112</strong><span>lessons<br/>24 hours</span></div></div><div className="lessons-layout"><div className="module-list"><div className="module-list-heading"><h3>Lesson List</h3><span>7 modules</span></div>{modules.map((item,i)=><details className="module-accordion" key={item.title} open={i===0}><summary><span className="module-number">0{i+1}</span><span className="module-summary-title">{item.title}<small>{item.count} lessons</small></span><ChevronRight size={18}/></summary><p>{item.description}</p>{['Understanding Digital Elements','Navigating Design Software Tools','Getting Started with Creative Assets'].slice(0,i===0?3:1).map((lesson,j)=><LessonRow key={lesson} number={`${i+1}.${j+1}`} title={lesson} duration={`${12+j*5} mins`} active={i===0&&j===0}/>)}</details>)}</div><aside className="lesson-preview-panel"><div className="lesson-video"><CourseCover course={course} large/><button className="video-play"><Play fill="currentColor"/></button><span className="lesson-video-badge">LESSON 01</span></div><span className="eyebrow">MODULE 01 · LESSON 01</span><h3>Understanding Digital Elements</h3><p>Learn the essential building blocks of digital asset creation and how each element works together.</p><div className="lesson-progress"><span>Course progress</span><b>1 of 112 lessons</b><div className="progress-track"><i style={{width:'7%'}}/></div></div><Link to="/course" className="text-link">Back to course overview <ArrowRight size={15}/></Link></aside></div><section className="learning-notes"><div><span className="eyebrow">YOUR LEARNING JOURNEY</span><h2>Everything you need to keep moving forward.</h2></div><div><h3>Lesson Content</h3><p>Engage with each lesson through captivating video content, detailed explanations, and interactive elements. Download resources, complete assignments, and test your understanding with quizzes.</p></div><div><h3>Lesson Progress Tracking</h3><p>See your growth as you complete lessons, with an intuitive progress tracker guiding your learning journey.</p></div></section></div></PageShell>
}

export function ReviewsPage() {
  const [rating,setRating]=useState('All rating')
  return <PageShell><CourseIntro active="Reviews"/><section className="section wrap reviews-page"><div className="reviews-heading"><div><span className="eyebrow">LEARNER FEEDBACK</span><h2>What Learners Are Saying</h2><p>Discover what our learners have to say about their experience with this course.</p></div><div className="rating-summary"><strong>4.7</strong><RatingStars rating={5}/><span>Based on <b>720</b> reviews</span></div></div><div className="ratings-overview"><div className="rating-overview-title"><h3>Ratings</h3><span>720 total ratings</span></div>{[5,4,3,2,1].map((n,i)=><div className="rating-bar-row" key={n}><span>{n} <Star size={13} fill="currentColor"/></span><div className="rating-track"><i style={{width:`${[74,15,6,3,2][i]}%`}}/></div><small>{[532,120,42,18,8][i]}</small></div>)}</div><div className="review-list-heading"><h3>Individual Reviews <span>(720)</span></h3><div className="review-filters">{['All rating','5','4','3','2','1'].map(v=><button className={rating===v?'review-filter-active':''} key={v} onClick={()=>setRating(v)}>{v}{v==='All rating'?'':' ★'}</button>)}</div></div><div className="review-grid">{reviews.map((item,i)=><article className="review-card" key={item.name}><div className="review-card-head"><Avatar initials={item.initials} tone={i}/><div><b>{item.name}</b><span>{item.role}</span></div><MoreHorizontal size={19}/></div><div className="review-card-rating"><RatingStars/><span>{item.date}</span></div><p>{item.body}</p><button className="helpful-button"><Heart size={16}/> Helpful <span>12</span></button></article>)}</div><div className="pagination"><button>‹</button><button className="page-active">1</button><button>2</button><button>3</button><span>…</span><button>72</button><button>›</button></div></section></PageShell>
}

export function CreatorPage() {
  return <PageShell><section className="creator-profile-hero"><div className="creator-banner"><span className="banner-disc"/><span className="banner-ring"/><span className="banner-corner">CREATE / SHARE / GROW</span></div><div className="wrap creator-profile-content"><div className="creator-profile-heading"><Avatar initials="PP" tone={4} size="large"/><div><span className="eyebrow">FEATURED CREATOR</span><h1>PurePearl Studio <BadgeCheck size={22}/></h1><p>Passionate UI/UX, Web designer</p></div><Button variant="blue">Follow creator <span>+</span></Button></div><div className="creator-bio"><div><h2>About the creator</h2><p>Welcome to the creative world of PurePearl Studio. Here, you'll discover the passion, expertise, and inspiration that drive a creative journey. Dive into my portfolio, showcasing a glimpse of my artistic endeavors. Each piece tells a unique story. Explore the world of creativity with me.</p><Link to="#portfolio" className="text-link">View portfolio <ArrowUpRight size={16}/></Link></div><div className="creator-metrics"><div><strong>6</strong><span>Courses</span></div><div><strong>2.4K</strong><span>Students</span></div><div><strong>4.8<Star size={16} fill="currentColor"/></strong><span>Creator rating</span></div></div></div></div></section><section className="section wrap creator-courses"><div className="section-row"><div><span className="eyebrow">PUREPEARL STUDIO</span><h2>Courses by this creator</h2></div><FilterSelect label="Sort by" value="Most relevant"/></div><div className="creator-filter-row"><FilterSelect label="Level" value="All levels"/><FilterSelect label="Category" value="All categories"/><div className="creator-view-tabs"><button className="view-active">Courses</button><button>Portfolio</button></div></div><div className="course-grid">{courses.map(item=><CourseCard key={item.title} course={item}/>)}</div><div className="center-action"><Button variant="outline">Load more courses <ArrowRight size={16}/></Button></div></section></PageShell>
}

export function NotFoundPage() {
  return <PageShell><section className="not-found wrap"><div className="not-found-graphic"><span className="not-found-orbit"/><strong>404</strong><span className="not-found-spark">✳</span></div><span className="eyebrow">OOPS! WRONG TURN</span><h1>The page you are looking for doesn’t exist</h1><p>Try to use a correct URL or go back to homepage to start again.</p><Link to="/"><Button>Back to Home <ArrowRight size={17}/></Button></Link></section></PageShell>
}
